(defun fizz (x)
  (cond ((zerop x) nil)
        ((equal (mod x 15) 0) (format t "FIZZBUZZ"))
        ((equal (mod x 5) 0) (format t "FIZZ"))
        ((equal (mod x 3) 0) (format t "BUZZ"))
        (t (format t "~S" x))))
(defun fizzbuzz ()
  (dotimes (i 100)
    (fizz i)))
